require('dotenv').config();
const prisma = require('./config/prisma');

const products = [
  {
    name: 'Aero Wireless Headphones',
    description: 'Premium over-ear Bluetooth headphones with deep bass, active noise cancellation, and up to 30 hours of battery life for immersive listening on the go.',
    price: 6599,
    category: 'Electronics',
    tags: ['wireless', 'bluetooth', 'audio', 'headphones', 'noise cancellation'],
    imageURL: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
    stock: 25,
  },
  {
    name: 'Urban Trail Backpack',
    description: 'Water-resistant everyday backpack with a padded laptop sleeve, hidden pockets, and breathable support for work, university, and weekend travel.',
    price: 2499,
    category: 'Bags',
    tags: ['backpack', 'travel', 'laptop bag', 'water resistant', 'daily use'],
    imageURL: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
    stock: 40,
  },
  {
    name: 'Terra Ceramic Coffee Mug',
    description: 'Minimalist ceramic mug with a comfortable matte finish, designed for espresso, tea, or your daily brew in a modern kitchen setup.',
    price: 499,
    category: 'Home',
    tags: ['coffee', 'mug', 'ceramic', 'kitchen', 'drinkware'],
    imageURL: 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&w=800&q=80',
    stock: 60,
  },
  {
    name: 'Luma Smart Watch',
    description: 'Slim fitness watch with heart-rate tracking, sleep analysis, and seamless smartphone notifications for a healthier, more connected lifestyle.',
    price: 7999,
    category: 'Wearables',
    tags: ['smart watch', 'fitness', 'health', 'tracker', 'wearable'],
    imageURL: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=800&q=80',
    stock: 18,
  },
  {
    name: 'Nordic Desk Lamp',
    description: 'Warm ambient desk lamp with touch dimming, USB charging, and a clean Scandinavian silhouette that elevates any workspace or bedroom.',
    price: 1899,
    category: 'Home',
    tags: ['lighting', 'desk lamp', 'workspace', 'home decor', 'ambient'],
    imageURL: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80',
    stock: 32,
  },
  {
    name: 'Peak Running Shoes',
    description: 'Lightweight running sneakers with cushioned support, breathable mesh, and durable grip for everyday training and city runs.',
    price: 4299,
    category: 'Sports',
    tags: ['running', 'shoes', 'sports', 'fitness', 'outdoor'],
    imageURL: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
    stock: 22,
  },
  {
    name: 'Verve Leather Wallet',
    description: 'Handcrafted genuine leather wallet with RFID protection, multiple card slots, and a slim profile for men and women.',
    price: 1699,
    category: 'Accessories',
    tags: ['wallet', 'leather', 'accessories', 'minimal', 'fashion'],
    imageURL: 'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=800&q=80',
    stock: 50,
  },
  {
    name: 'Vista 4K Streaming Stick',
    description: 'Compact streaming device with crisp 4K output, voice control, and instant access to your favorite shows, apps, and live channels.',
    price: 5499,
    category: 'Electronics',
    tags: ['streaming', '4k', 'tv', 'entertainment', 'device'],
    imageURL: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=800&q=80',
    stock: 27,
  },
  {
    name: 'Drift Cotton Throw',
    description: 'Soft woven throw blanket in a subtle neutral tone, ideal for reading corners, sofas, and cozy evenings at home.',
    price: 1299,
    category: 'Home',
    tags: ['blanket', 'throw', 'cotton', 'sofa', 'cozy'],
    imageURL: 'https://images.unsplash.com/photo-1517705008128-361805f42e86?auto=format&fit=crop&w=800&q=80',
    stock: 48,
  },
  {
    name: 'Orbit Travel Bottles Set',
    description: 'Leak-proof silicone toiletry kit with reusable containers for shampoos, lotions, and essential oils on all your journeys.',
    price: 899,
    category: 'Travel',
    tags: ['travel', 'toiletry', 'essential', 'bottles', 'portable'],
    imageURL: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
    stock: 70,
  },
  {
    name: 'Echo Mini Speaker',
    description: 'Pocket-sized wireless speaker delivering crisp, room-filling sound with deep bass and Bluetooth connectivity.',
    price: 2499,
    category: 'Electronics',
    tags: ['speaker', 'bluetooth', 'audio', 'portable', 'music'],
    imageURL: 'https://images.unsplash.com/photo-1518444065439-e933c06ce9cd?auto=format&fit=crop&w=800&q=80',
    stock: 55,
  },
  {
    name: 'Harbor Insulated Bottle',
    description: 'Double-walled stainless steel bottle that keeps drinks cold for 24 hours and hot for 12 hours, perfect for commuting.',
    price: 1099,
    category: 'Travel',
    tags: ['bottle', 'hydration', 'travel', 'steel', 'fitness'],
    imageURL: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=800&q=80',
    stock: 68,
  },
  {
    name: 'Breeze Yoga Mat',
    description: 'Eco-friendly non-slip yoga mat with extra cushioning for comfort, balance, and floor workouts at home or in the studio.',
    price: 1999,
    category: 'Sports',
    tags: ['yoga', 'fitness', 'exercise', 'mat', 'wellness'],
    imageURL: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=800&q=80',
    stock: 36,
  },
  {
    name: 'Nova Ceramic Planter',
    description: 'Modern ceramic planter with a matte finish and drainage hole for herbs, succulents, and indoor greenery.',
    price: 899,
    category: 'Home',
    tags: ['plant', 'planter', 'ceramic', 'garden', 'home decor'],
    imageURL: 'https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?auto=format&fit=crop&w=800&q=80',
    stock: 41,
  },
  {
    name: 'Pace Wireless Charger',
    description: 'Fast wireless charging pad with a slim design and anti-slip base for your phone, earbuds, and other compatible devices.',
    price: 1499,
    category: 'Electronics',
    tags: ['charger', 'wireless', 'phone', 'tech', 'accessory'],
    imageURL: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&w=800&q=80',
    stock: 80,
  },
  {
    name: 'Golden Hour Sunglasses',
    description: 'UV-protective polarized sunglasses with a lightweight frame and sleek design for everyday comfort and style.',
    price: 2199,
    category: 'Accessories',
    tags: ['sunglasses', 'fashion', 'uv', 'accessory', 'summer'],
    imageURL: 'https://images.unsplash.com/photo-1577803947579-9f5f3d0b1d2a?auto=format&fit=crop&w=800&q=80',
    stock: 44,
  },
  {
    name: 'Cinder Coffee Grinder',
    description: 'Compact burr grinder with adjustable settings for a fresh, aromatic coffee experience every morning.',
    price: 3199,
    category: 'Kitchen',
    tags: ['coffee', 'grinder', 'kitchen', 'appliance', 'brew'],
    imageURL: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80',
    stock: 19,
  },
  {
    name: 'Summit Laptop Sleeve',
    description: 'Protective laptop sleeve with padded interior, premium finish, and zip closure for secure daily transport.',
    price: 1399,
    category: 'Bags',
    tags: ['laptop', 'sleeve', 'case', 'travel', 'work'],
    imageURL: 'https://images.unsplash.com/photo-1526948128573-703ee1aeb6fa?auto=format&fit=crop&w=800&q=80',
    stock: 62,
  },
  {
    name: 'Sculpt Desk Organizer',
    description: 'Minimal desktop organizer crafted to keep stationery, cables, and essentials neatly arranged on your desk.',
    price: 1199,
    category: 'Office',
    tags: ['desk', 'organizer', 'office', 'workspace', 'minimal'],
    imageURL: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=800&q=80',
    stock: 57,
  },
  {
    name: 'Bluewave Bluetooth Earbuds',
    description: 'Compact wireless earbuds with rich audio, secure fit, and a portable charging case for daily listening.',
    price: 3999,
    category: 'Electronics',
    tags: ['earbuds', 'bluetooth', 'audio', 'portable', 'wireless'],
    imageURL: 'https://images.unsplash.com/photo-1585386959984-a4155224a1ad?auto=format&fit=crop&w=800&q=80',
    stock: 29,
  },
  {
    name: 'Velvet Indoor Pillow',
    description: 'Soft-touch decorative pillow in a premium velvet finish that adds texture and comfort to seating areas.',
    price: 799,
    category: 'Home',
    tags: ['pillow', 'decor', 'velvet', 'living room', 'comfort'],
    imageURL: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80',
    stock: 90,
  },
  {
    name: 'Atlas Travel Towel',
    description: 'Lightweight microfiber towel designed to dry quickly, pack compactly, and handle travel, gym, and beach days.',
    price: 999,
    category: 'Travel',
    tags: ['towel', 'travel', 'microfiber', 'beach', 'gym'],
    imageURL: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
    stock: 72,
  },
  {
    name: 'Summit Foam Roller',
    description: 'High-density foam roller for stretching, recovery, and mobility work after exercise or long workdays.',
    price: 1299,
    category: 'Sports',
    tags: ['foam roller', 'recovery', 'fitness', 'wellness', 'mobility'],
    imageURL: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=800&q=80',
    stock: 33,
  },
  {
    name: 'Bloom Essential Oil Diffuser',
    description: 'Ultrasonic diffuser with soft ambient light and whisper-quiet operation for calming home and bedroom rituals.',
    price: 2499,
    category: 'Wellness',
    tags: ['diffuser', 'wellness', 'aroma', 'home', 'calm'],
    imageURL: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&w=800&q=80',
    stock: 24,
  },
  {
    name: 'Pixel Camera Tripod',
    description: 'Portable camera tripod with adjustable height, Bluetooth remote, and compact fold-flat design for creators.',
    price: 2999,
    category: 'Electronics',
    tags: ['tripod', 'camera', 'creator', 'photo', 'portable'],
    imageURL: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80',
    stock: 20,
  },
  {
    name: 'Horizon Sling Bag',
    description: 'Compact crossbody sling with smart compartments for everyday essentials, quick errands, and city commuting.',
    price: 1799,
    category: 'Bags',
    tags: [' sling', 'crossbody', 'city', 'travel', 'everyday'],
    imageURL: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80',
    stock: 46,
  },
  {
    name: 'Pure Cotton Towels Set',
    description: 'Ultra-soft cotton towel set with absorbent texture and neutral tones for bath, guest, and spa use.',
    price: 1999,
    category: 'Home',
    tags: ['towels', 'bath', 'cotton', 'spa', 'home'],
    imageURL: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=800&q=80',
    stock: 65,
  },
  {
    name: 'Basil Herb Grow Kit',
    description: 'Indoor herb starter kit with grow cups, nutrient pack, and easy instructions for home gardening.',
    price: 699,
    category: 'Garden',
    tags: ['herb', 'grow', 'garden', 'home', 'fresh'],
    imageURL: 'https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?auto=format&fit=crop&w=800&q=80',
    stock: 58,
  },
  {
    name: 'Flux USB-C Hub',
    description: 'Multi-port USB-C hub with HDMI, USB, and charging support for workstations, laptops, and mobile setups.',
    price: 2599,
    category: 'Electronics',
    tags: ['usb-c', 'hub', 'connectivity', 'laptop', 'work'],
    imageURL: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80',
    stock: 35,
  },
  {
    name: 'Monarch Notebook Set',
    description: 'Premium paper notebook set with ruled pages and elegant binding for journaling, planning, and ideas.',
    price: 899,
    category: 'Office',
    tags: ['notebook', 'paper', 'journal', 'planning', 'office'],
    imageURL: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=800&q=80',
    stock: 82,
  },
  {
    name: 'Cordova Leather Belt',
    description: 'Refined leather belt with a polished buckle, designed for day-to-day styling and long-lasting wear.',
    price: 2199,
    category: 'Fashion',
    tags: ['belt', 'leather', 'fashion', 'accessory', 'style'],
    imageURL: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
    stock: 31,
  },
  {
    name: 'Chrome Bluetooth Mouse',
    description: 'Ergonomic wireless mouse with silent clicks and a compact design tuned for productivity on the move.',
    price: 1499,
    category: 'Office',
    tags: ['mouse', 'wireless', 'office', 'computer', 'productivity'],
    imageURL: 'https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=800&q=80',
    stock: 74,
  },
  {
    name: 'Rainfall Shower Speaker',
    description: 'Water-resistant shower speaker with secure mount and rich sound for music and calls in the bathroom.',
    price: 1999,
    category: 'Wellness',
    tags: ['shower', 'speaker', 'waterproof', 'bathroom', 'audio'],
    imageURL: 'https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&w=800&q=80',
    stock: 28,
  },
  {
    name: 'Luna Read Lamp',
    description: 'Adjustable reading lamp with warm glow, USB charging, and a sleek arc design for bedrooms and study corners.',
    price: 1799,
    category: 'Home',
    tags: ['reading', 'lamp', 'bedroom', 'study', 'lighting'],
    imageURL: 'https://images.unsplash.com/photo-1517191434949-5e90cd67d2b6?auto=format&fit=crop&w=800&q=80',
    stock: 39,
  },
  {
    name: 'Prism Wall Clock',
    description: 'Modern wall clock with a clean silhouette and quiet mechanism for interiors with minimalist styling.',
    price: 1299,
    category: 'Home',
    tags: ['clock', 'wall decor', 'home', 'modern', 'minimal'],
    imageURL: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80',
    stock: 54,
  },
  {
    name: 'Glide Skateboard',
    description: 'Street-ready skateboard with durable wheels and a stable deck built for commuters and casual riders.',
    price: 3499,
    category: 'Sports',
    tags: ['skateboard', 'outdoor', 'street', 'sport', 'ride'],
    imageURL: 'https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?auto=format&fit=crop&w=800&q=80',
    stock: 17,
  },
  {
    name: 'Aster Air Fryer',
    description: 'Compact air fryer that delivers crispy results with less oil and faster cooking for busy weeknights.',
    price: 4599,
    category: 'Kitchen',
    tags: ['air fryer', 'kitchen', 'cooking', 'appliance', 'healthy'],
    imageURL: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?auto=format&fit=crop&w=800&q=80',
    stock: 21,
  },
  {
    name: 'Pinewood Cutting Board',
    description: 'Durable wooden cutting board with a smooth finish and generous prep area for everyday kitchen tasks.',
    price: 1299,
    category: 'Kitchen',
    tags: ['cutting board', 'wood', 'kitchen', 'chef', 'prep'],
    imageURL: 'https://images.unsplash.com/photo-1592150621744-accd7b2a6a2f?auto=format&fit=crop&w=800&q=80',
    stock: 63,
  },
  {
    name: 'Crete Compact Mirror',
    description: 'Travel compact mirror with a foldable design and soft-touch finish for quick touch-ups anywhere.',
    price: 599,
    category: 'Beauty',
    tags: ['mirror', 'beauty', 'travel', 'compact', 'personal care'],
    imageURL: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80',
    stock: 84,
  },
  {
    name: 'Mira Face Roller',
    description: 'Facial roller for massage and skin-care rituals designed to help reduce puffiness and add a calming routine.',
    price: 1199,
    category: 'Beauty',
    tags: ['skincare', 'roller', 'beauty', 'massage', 'self care'],
    imageURL: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=800&q=80',
    stock: 30,
  },
  {
    name: 'Vela Silk Scarf',
    description: 'Lightweight silk scarf with a soft drape and vibrant print for effortless layering and elevated styling.',
    price: 1899,
    category: 'Fashion',
    tags: ['scarf', 'silk', 'fashion', 'style', 'accessory'],
    imageURL: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=800&q=80',
    stock: 27,
  },
  {
    name: 'Core Resistance Bands',
    description: 'Set of durable resistance bands for strength training, mobility work, and home workouts with adjustable intensity.',
    price: 1199,
    category: 'Sports',
    tags: ['bands', 'fitness', 'strength', 'exercise', 'home gym'],
    imageURL: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=800&q=80',
    stock: 61,
  },
  {
    name: 'Hush Sleep Mask',
    description: 'Soft contoured eye mask made for restful nights, travel, and better sleep in any environment.',
    price: 799,
    category: 'Wellness',
    tags: ['sleep', 'mask', 'travel', 'wellness', 'rest'],
    imageURL: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&w=800&q=80',
    stock: 71,
  },
  {
    name: 'Delta Travel Adapter',
    description: 'Universal travel adapter with multiple plug options and USB ports for seamless charging around the world.',
    price: 1499,
    category: 'Travel',
    tags: ['adapter', 'travel', 'charger', 'international', 'power'],
    imageURL: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&w=800&q=80',
    stock: 52,
  },
  {
    name: 'Northstar Portable SSD',
    description: 'Compact high-speed solid-state drive for effortless backups, file transfer, and mobile storage on the move.',
    price: 6999,
    category: 'Electronics',
    tags: ['storage', 'ssd', 'portable', 'data', 'tech'],
    imageURL: 'https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?auto=format&fit=crop&w=800&q=80',
    stock: 16,
  },
  {
    name: 'Korin Keyboard Cover',
    description: 'Protective keyboard cover that keeps your workspace clean while adding a smooth, comfortable typing feel.',
    price: 899,
    category: 'Office',
    tags: ['keyboard', 'cover', 'workspace', 'computer', 'protection'],
    imageURL: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80',
    stock: 66,
  },
  {
    name: 'Cedar Lunch Box',
    description: 'Insulated lunch box with separate compartments for fresh, tidy meals at work or on the go.',
    price: 1499,
    category: 'Kitchen',
    tags: ['lunch box', 'storage', 'food', 'travel', 'daily use'],
    imageURL: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=800&q=80',
    stock: 49,
  },
  {
    name: 'Aster Throw Pillow Pair',
    description: 'Set of coordinated throw pillows in a textured weave for soft comfort and layered home styling.',
    price: 1799,
    category: 'Home',
    tags: ['pillow', 'home decor', 'living room', 'cozy', 'textile'],
    imageURL: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80',
    stock: 42,
  },
  {
    name: 'Quill Writing Pen Set',
    description: 'Premium pen set with smooth ink flow, balanced weight, and elegant finishes for gifting or desk use.',
    price: 1099,
    category: 'Office',
    tags: ['pen', 'writing', 'gift', 'desk', 'office'],
    imageURL: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=800&q=80',
    stock: 78,
  },
  {
    name: 'Solstice Water Bottle',
    description: 'Leak-proof hydration bottle with ergonomic grip and easy-sip lid for workouts, commutes, and outdoor trips.',
    price: 999,
    category: 'Sports',
    tags: ['water bottle', 'hydration', 'gym', 'travel', 'fitness'],
    imageURL: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=800&q=80',
    stock: 75,
  },
  {
    name: 'Mosaic Wall Art',
    description: 'Decorative wall art with layered color and handcrafted texture to create a warm focal point in any room.',
    price: 2899,
    category: 'Home',
    tags: ['art', 'decor', 'wall', 'living room', 'home'],
    imageURL: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80',
    stock: 23,
  },
  {
    name: 'Signal Smart Thermometer',
    description: 'High-accuracy digital thermometer with quick readings and easy-to-read display for daily health tracking.',
    price: 1599,
    category: 'Wellness',
    tags: ['health', 'thermometer', 'wellness', 'care', 'digital'],
    imageURL: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=800&q=80',
    stock: 36,
  },
  {
    name: 'Surf Travel Duffle',
    description: 'Water-resistant duffle with soft grip handles and modular storage for weekend escapes and training sessions.',
    price: 3499,
    category: 'Travel',
    tags: ['duffle', 'travel', 'weekend', 'bag', 'outdoor'],
    imageURL: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=800&q=80',
    stock: 14,
  }
];

const seedProducts = async () => {
  console.log('Seeding product catalog into Prisma...');

  for (const productData of products) {
    const existingProduct = await prisma.product.findFirst({
      where: { name: productData.name }
    });

    if (existingProduct) {
      await prisma.product.update({
        where: { id: existingProduct.id },
        data: productData,
      });
    } else {
      await prisma.product.create({
        data: productData,
      });
    }
  }

  console.log(`Seeded ${products.length} products successfully.`);
};

seedProducts()
  .catch((error) => {
    console.error('Product seed failed:', error.message);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
